### ISSUE TITLE
Could not find com.github.sevar83:android-spatialite:n-support-SNAPSHOT.

### ISSUE THREAD

**Issue by aholong** [sevar83/SpatiAtlas#1]
Hi Sevar83, I had the following error:
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.sevar83:android-spatialite:n-support-SNAPSHOT.
     Required by:
         project :app

Does anybody else have the same issue?

**Comment by svkostadinoff** [comment]
Hi, it will require some time to fix it because I need to contact the JitPack.io support. Apparently some of their latest server upgrades of the NDK have broken the build of https://github.com/sevar83/android-spatialite and this library is used as a base for SpatiAtlas app.

**Comment by svkostadinoff** [comment]
The problem should be fixed with the latest commits. Please check it out.

**Comment by aholong** [comment]
Many thanks sevar83. This problem seems to be solved. But the project still doesn't run properly. I had the following error now:
Error:Cause: null value in entry: gmapsV2ApiKey=null

I guess I need to get a key for google maps, which I did. But where should I put the key in the code? I tried put it in the manifest file but it didn't work.

Thanks in advance.

**Comment by svkostadinoff** [comment]
The problem is that you need to register a Google Maps v2 API key and put
it in Gradle local.properties file as `gmapsV2ApiKey=<your key>`. There's
no other way to run Google Maps without this key and its personal, everyone
running the example must use it its own key.
